const cities = ['New York', 'Rome', "Moscow", "Tokyo", "Paris", "London", "Berlin", "Madrid", "Beijing", "Istanbul"];

// Log the result after each task:

// 1. Add an element to the end of the array...

// 2. Add an element to the beginning of the array...

// 3. Remove an element from the end of the array...

// 4. Remove an element from the beginning of the array...

// 5. Remove the element at index 2...

// 6. Remove the element 'Paris'...
